In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[-2]

9

In [6]:
b = a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
c=b.view()
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
b[6]=12
c

array([ 1,  2,  3,  4,  5,  6, 12,  8,  9, 10])

In [13]:
d=b.reshape(5,2)
d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [12,  8],
       [ 9, 10]])

In [16]:
f= np.array([11,12,13,14])
g=np.concatenate((b,f))
g

array([ 1,  2,  3,  4,  5,  6, 12,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.array_split(g,3)

[array([1, 2, 3, 4, 5]), array([ 6, 12,  8,  9, 10]), array([11, 12, 13, 14])]

In [18]:
np.where(g==6)

(array([5], dtype=int64),)

In [19]:
np.where(g%2==0)

(array([ 1,  3,  5,  6,  7,  9, 11, 13], dtype=int64),)

In [21]:
h=np.array([3,5,1,7,2])
np.sort(h)

array([1, 2, 3, 5, 7])

In [22]:
i= np.array([[1,7,10,6,3],[5,8,2,19,11]])
np.sort(i)

array([[ 1,  3,  6,  7, 10],
       [ 2,  5,  8, 11, 19]])

In [24]:
fruit= np.array(['grapes',"apple","mango"])
np.sort(fruit)

array(['apple', 'grapes', 'mango'], dtype='<U6')

In [37]:
np.random.randint(100)

80

In [39]:
np.random.rand()

0.21933538365033034

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])